GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlNoaXYiLCJpYXQiOjE2NTI3OTM1MzAsImV4cCI6MTY1Mjc5MzU2MH0.NpY7jqtFKA8SkHBCVnMNbPg88foJ2hmQ6x4_d_KvOHs

###


# POST http://localhost:3001/login
# Content-Type: application/json

# {
#     "userName": "Shiv"
# }

###


DELETE  http://localhost:4001/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlNoaXYiLCJpYXQiOjE2NTI3OTM0ODl9.FBeciXTddYjAqNFpeha5ryo8MxAt7Qcaa9B-pAUcWf8"
}

###

POST http://localhost:4001/login
Content-Type: application/json

{
    "userName": "Shiv"
}

###

POST http://localhost:4001/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlNoaXYiLCJpYXQiOjE2NTI3OTM0ODl9.FBeciXTddYjAqNFpeha5ryo8MxAt7Qcaa9B-pAUcWf8"
}